language: c
compiler:
    - gcc
    - clang
before_install:
    - echo "yes" | sudo add-apt-repository ppa:gnome3-team/gnome3
    - sudo apt-get update -qq
    - sudo apt-get install -qq libudisks2-dev
script: make
